### ISSUE TITLE
Please what does fx2.mk contain?

### ISSUE THREAD

**Issue by lambertdw** [rpcope1/Hantek6022API#19]
Hantek6022API-master/PyHT6022/HantekFirmware/custom/

include $(FX2LIBDIR)/lib/fx2.mk

Meanwhile I'll try to build using sdcc assuming the Makefile target is fw.

**Comment by rpcope1** [comment]
Should be this file: https://github.com/djmuhlestein/fx2lib/blob/4d3336c3b5ebc2127a8e3c013ea13ad58873e9e0/lib/fx2.mk

Have you initialized the submodules? Fx2lib is included as a submodule dependency. If you're having a hard time building, you might try something like:

```
    git submodule update --init --recursive
```

Submodules are kind of ugly in git, but I think Jochen and I had decided that was the easiest way to bundle that dependency. Let me know if that works for you and if you have any other questions.

**Comment by lambertdw** [comment]
dwl$ pwd
/home/lambertdw/downloads/installs/Hantek6022API-master/PyHT6022/HantekFirmware/custom
dwl$ git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

**Comment by rpcope1** [comment]
So, you might want to execute that command from the base directory of the repository, which in your case is potentially /home/lambertdw/downloads/installs/Hantek6022API-master/

Did you "git clone" the repository, or pull the zip from Github?

**Comment by lambertdw** [comment]
2 hidden git files are in the base directory.  I pulled the zip from Github.

dwl$ pwd
/home/lambertdw/downloads/installs/Hantek6022API-master
dwl$ ls -a
.                         .gitmodules                    README.md
..                        HT6022BEBuiltInOscillator.png  REVERSE_ENGINEERING.md
60-hantek-6022-usb.rules  LICENSE                        setup.py
examples                  PyHT6022
.gitignore                PyHT6022Tests
dwl$ git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
dwl$

**Comment by rpcope1** [comment]
So yeah, this is an issue with just downloading the zip; I should probably push a warning to the repository about it. The best way to get the repository is to clone with git:

```
git clone --recursive https://github.com/rpcope1/Hantek6022API.git
```

It looks like the issue with submodules not getting packaged with zips maybe an ongoing thing, but it looks like you have a git client present, so if you blow away the repository directory generated from the zip then in git clone with the recursive option like shown above, you should be set to go.

Hopefully this is helpful.

**Comment by rpcope1** [comment]
I am going to assume you got this to work OK. If not, feel free to reopen the ticket.

**Comment by lambertdw** [comment]
Thank you for your quick responses and ideas, and for teaching me how to 
use git.

At this point I'm stuck finding the usb1 python2.7 code.  Well, I'm 
supposed to be a python expert.  So I'm converting the source for 
python3 which when/if done I'll pass back to you.

**Comment by rpcope1** [comment]
Very cool. If you need any help at all just shoot me a message, and I'm pretty sure I'll be able to take a look. As far as Python 3, I imagine there are some non-Python 3 bits in there; I highly recommend looking at the Six package as it provides a lot of stuff for Python 2/3 interop. Just as a heads up I want to make sure we have backwards compatibility to at least Python 2.7 (if not 2.6), so if you're writing or modifying code for this repo, it might be something to keep in mind (you could certainly help me out that way :) ).

**Comment by lambertdw** [comment]
python3 effort status:

python3 examples/example_linux_scopevis.py

```
With pdb.set_trace() active, mostly single stepping, and with probe
connected to the square wave generator I obtained a square wave plot.

Without debugging on other trials scope.read_data() returned lengths
of data between 500 and 700 where 8192 are requested.
I inserted time.sleep() between a few likely looking spots---no
help; and set timeout to 1, also no help.  And now I'm getting

usb1.USBErrorOverflow: LIBUSB_ERROR_OVERFLOW [-8]
```

example_linux_recordwav.py

```
The read_async method seems to work, hooking the oscilloscope data
up with audacity is inspired, without having moved the probes the
trace looks periodically regular-ish.  Which is not the same as "Wow
I'm seeing the obvious square wave I'd expected!"
```

flash & read firmware work as best I can tell,

continuous_read works. (read_async)

perf_test and read_eeprom generate the LIBUSB_ERROR_OVERFLOW error.

**Comment by rpcope1** [comment]
Sorry for the delay. Hmm...I have seen the mysterious extra short traces before, I will have to take a look at that again. What sample rate did you set the scope to? I'd need to go look at the way the Python libusb wrapper interacts with the underlying library, but I think I have seen these errors before. 

One suggestion, is that because the scope is using USB bulk transfer (versus the experimental isochronous mode Jochen wrote), other USB traffic on that bus will often take precedence. I strongly suggest (if you didn't already know) that the scope be run separate on it's own bus, if possible. You can verify this with

```
$ lsusb
```

You should see a device with an ID like ID xxxx:6022, and hopefully it should be on it's own bus. This may help the LIBUSB_ERROR_OVERFLOW. Can you tell me a little bit also about the computer you're running this against? I'll see if I can't reproduce this (and debug) this weekend. I'm super stoked you're managing to get this to work with Python 3; just drop a line if you run into anything else with the library.

**Comment by lambertdw** [comment]
I won't get to this until mid-next week.  Thanks.

**Comment by lambertdw** [comment]
My computer is a thinkpad W540.  After initializing the scope, and 
removing computer from docking station ``lsusb --verbose'' shows that 
the oscilloscope is the only active device.  Cannot open other devices.  
Thank you, the scope works better without mouse/keyboard/phone on same 
bus.   I don't have full success, here's a failure and a success:
$ python3 ./examples/example_linux_scopevis.py
data lengths differ!
[('timing', 8192), ('voltage', 584)]
$ python3 ./examples/example_linux_scopevis.py
$

Attached are python3 files.  I expect them to be compatible with python 
2.7.  Most of the changes involved changing xrange to range and setting 
up print as print(formatted_string) which will look the same in python2 
and python3.  There was one instance where i made an explicitly version 
dependent call to a usblib function.

I renamed the original .py files as .py2, modified these into .py3, then 
linked either version as .py.  I made the py3.tar file using appropriate 
bash commands:

$ pwd
/home/lambertdw/downloads/installs/Hantek6022API
$ tar cf py3.tar $( find . -name '*.py3' -print )

I would think you can safely extract the files named  .py3 with tar xpf 
py3.tar
And then to do the linking trick you'd need to first rename your .py 
files as .py2

Untested commands I did this a while ago:
find . -name '_.py' -exec mv {} {}2 \;
And then to use one version or the other, say the .py3 files
find -name '_.py' -exec rm -f {} \; -exec ln {}3 {} \;

**Comment by jhoenicke** [comment]
I tried example_linux_scopevis yesterday and didn't get it to run under python 2.7 out of the box.  Maybe something has broken recently.  I tried to debug it, but the problem seems to be with usb_bulk_read always complaining without reading anything.

Looks like file attachments do not work in github issues.   I suggest you fork the repository, add a python3 branch and open a pull-request.  This way we can discuss this there (without merging the pull request).  Just overwrite the python2 files, this makes it easier to compare them.  In case you are not familiar with git the procedure is as follows:
1. Add your github repository as new remote connection in you local 
   Hantek6022API directory with
   
   `git remote add lambertdw git@github.com:lambertdw/Hantek6022API`
2. Create a new branch:
   
   `git checkout -b python3`
3. Copy over the python3 files, and commit them with
   
   `git commit -a`
   
   This opens an editor where you can describe your changes.  In the bottom it also mentions which files are tracked.  If there are untracked files that are important you need to add them with `git add` (you can abort the commit by quitting the editor without any changes).
4. Push the changes to your forked repository:
   
   `git push lambertdw python3`
5. Go to https://github.com/lambertdw/Hantek6022API
   switch to python3 branch and click the green compare, review, pull request button.

**Comment by rpcope1** [comment]
As far as things being broke in Python 2.7, I'll take a look. This has kind of been on the back-burner as I'm trying to juggle a bunch of eggs here. 

@lambertdw I think Jochen is spot on the money there. Open a pull request if you've got Python 3 changes, and I'll check it out here, and we'll see what can be done about bringing it into the current code base.

I am planning on doing some clean-up in this repository, and writing tests (should have done that from the beginning). There's probably a lot of gross things I've left on the Python, side and documentation is still lacking. Hopefully in the next couple of weeks (or sooner), I'll have some time...

**Comment by lambertdw** [comment]
Results of following the instruction list---I think there was a 
failure.  I also didn't understand the "copy over the python3 files".  I 
modified the files for python2/3 compatibility directly in the same 
places they were at checkout, and I didn't find any new branches in the 
.git directory.

dwl$ pwd
/home/lambertdw/downloads/installs/Hantek6022API
dwl$ git remote add lambertdw git@github.com:lambertdw/Hantek6022API
dwl$ git checkout -b python3
M    PyHT6022/HTSDKScope.py
M    PyHT6022/HantekFirmware/**init**.py
M    PyHT6022/HantekFirmware/custom/build/firmware.ihx
M    PyHT6022/HantekFirmware/fx2lib
M    PyHT6022/LibUsbScope.py
M    PyHT6022Tests/LibUsbScopeTest.py
M    examples/example_linux_continous_read.py
M    examples/example_linux_perf_test.py
M    examples/example_linux_readeeprom.py
M    examples/example_linux_readfirmware.py
M    examples/example_linux_recordwav.py
M    examples/example_linux_scopevis.py
M    examples/example_recordwav.py
M    examples/example_scopevis.py
Switched to a new branch 'python3'
dwl$ git config --global user.email b49p23tivg@gmail.com
dwl$ git commit -a -m 'python3 support, no python2 syntax errors, 
otherwise untested with python2.'
[python3 0e2ab98] python3 support, no python2 syntax errors, otherwise 
untested with python2.
  13 files changed, 374 insertions(+), 353 deletions(-)
  rewrite PyHT6022/HantekFirmware/custom/build/firmware.ihx (88%)
dwl$ git push lambertdw python3
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes

Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list 
of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
dwl$

**Comment by jhoenicke** [comment]
Quick answer: you have to create a private/public key pair for SSH and register your public key with your github account on the github settings page.  Once you have done this, you should be able to connect with `ssh git@github.com` (it should just print a message and log you out again).

Then `git push` should work.

See the github documentation for more details.

**Comment by lambertdw** [comment]
Success, we have a python3 branch.  Looks like I pushed
PyHT6022/HantekFirmware/custom/build/firmware.ihx

back to the stone ages however.  Has the firmware.ihx file changed since 
I last updated my code versions?

Step 5) Go to https://github.com/lambertdw/Hantek6022API 
https://github.com/lambertdw/Hantex6022API
switch to python3 branch and click the green compare, review, pull 
request button.
