### ISSUE TITLE
Linux, script freezes when flashing firmware

### ISSUE THREAD

**Issue by Kezii** [rpcope1/Hantek6022API#22]
Hi, on Arch linux, when i do `python2 examples/example_linux_flashfirmware.py`, the script starts but it stops at `scope.flash_firmware()`, and stays there, without giving errors or output.
Am i doing something wrong? The scope is connected, the firmware is built as instruction said.

Python 2.7.10

**Comment by lambertdw** [comment]
File Hantek6022API/PyHT6022/LibUsbScope.py has a method
     def flash_firmware(self, firmware=default_firmware, 
supports_single_channel=True, timeout=60):

has a delay loop

```
     time.sleep(.5)
     while not self.setup():
         time.sleep(0.1)
```

maybe you could include some sort of diagnostic information display 
within that loop
             print('yet another iteration')

You'll also notice before that is a timeout for writing packets, which 
is probably where your code hangs.
My Hantek oscilloscope does not have a "power on" indicator light. A 
defect in the design, in my opinion.

Certain you've connected the scope to a USB port and not a USB3 port?  
(probably not possible within reason)
Certain that the port on your computer works?

Dave

**Comment by lambertdw** [comment]
I point out these delays as you should expect the code to take a 
while---on my system it takes a few seconds.  Sounds like you've waited 
much longer.

**Comment by Kezii** [comment]
Thanks for the answer, i made some investigation as you suggested and i found that the script stops at this line:
`bytes_written = self.device_handle.controlWrite(0x40, self.RW_FIRMWARE_REQUEST,
                                                            packet.value, self.RW_FIRMWARE_INDEX,
                                                            packet.data, timeout=timeout)`
https://github.com/rpcope1/Hantek6022API/blob/master/PyHT6022/LibUsbScope.py#L138

It stayed there for over two minutes without responding.

I tried on the laptop (arch linux too), and i have the same problem. I tried on windows and the scope works. I connected it on a usb2 port on both PCs (the ports are working)

I don't know if i'm missing something, i followed the readme, here's exactly what i did:

```
git clone https://github.com/rpcope1/Hantek6022API.git
cd Hantek6022API/
sudo cp 60-hantek-6022-usb.rules /lib/udev/rules.d/
sudo udevadm control --reload-rules
yaourt -S sdcc
git submodule update --init
cd PyHT6022/HantekFirmware/custom
make
cd ../../../
sudo python2 setup.py install
python2 examples/example_linux_flashfirmware.py 
```

Thanks again

**Comment by rpcope1** [comment]
Keep in mind, this repository uses entirely different firmware for the
scope than the Windows version, so I wouldn't be too worried if one worked
but not the other.

My apologies for not having much in the way of support here, I've got a
number of other projects for both work and clients that are critically
pressing and I've not had a whole lot of time to give this repository the
attention it deserves.

As far as setup not working, can you give me the output of lsusb when the
scope is plugged in? The setup works by targeting a certain ID to flash,
and also requires you to have set the udev rules correctly for the scope.
Have you added those rules? Does the script work correctly when run as root?

Something I discovered about the codebase here is that in order to do
anything really interesting, you have to push very hard on what is possible
with the Python interpreter, speed-wise. The GIL also makes life awful
here, as easy parallelization via threads is crippled in a CPU bound
workload like this. What really needs to happen for this to be any good is
someone (myself or whoever) needs to throw away at least part of the Linux
library, and either reimplement in C or Cython, and then bind it in via
CFFI. If you or anyone else wants to help do that, I'd certainly entertain
trying to slice some time out to get this moving in the near future.

**Comment by Kezii** [comment]
> I've got a number of other projects for both work and clients that are critically pressing

I understand that, it's ok

> As far as setup not working, can you give me the output of lsusb when the scope is plugged in?

This is the scope line:
`Bus 001 Device 007: ID 04b4:6022 Cypress Semiconductor Corp.`

> Have you added those rules? Does the script work correctly when run as root?

Yes i added the rules as i said in the previous message, running as root don't change much.

> and either reimplement in C

This is exactly what i wanted to do, maybe to make a kernel module for the scope, or at least have a C/C++ implementation, i saw this project and i wanted to take this as a starting point but i can't make it work.

By the way,
I have some updates on the problem, the for loop where the "blocking" function is (`for packet in firmware:`), seems to slowly iterate, at about one iteration per minute (the timeout argument?), i left it there for more than 10 minutes, i see it's slowly looping (i added some prints) but i don't think this is an intended behaviour... And it didn't go anywhere

**Comment by stapelberg** [comment]
I’m having the same issue. I added a bunch of print statements:

``` python
print 'writing byte'
bytes_written = self.device_handle.controlWrite(0x40, self.RW_FIRMWARE_REQUEST,
                                                        packet.value, self.RW_FIRMWARE_INDEX,
                                                        packet.data, timeout=timeout)
print 'bytes_written = %s' % str(bytes_written)
```

And what I see on the console is:

```
writing byte
bytes_written = 1
writing byte
bytes_written = 4
writing byte
bytes_written = 1
writing byte
[…]
```

With 1 minute passing each time “writing byte” is printed.

**Comment by baruch** [comment]
I get the same issue, loading has a timeout on each transfer of one minute even if I set the timeout to 1 second in the code.

I can load the firmware with cycfx2prog and it is very fast then but the utilities with this repo code are still very slow.
